spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quind
    username: postgres
    password: brigadier
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    user: postgres
    password: brigadier
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8181
  servlet:
    context-path: /Prueba-tecnica
